version: '3'
services:
  #PHP Service
  webbanhang_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: webbanhang_app
    container_name: webbanhang_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: webbanhang_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - webbanhang-network

  #Nginx Service
  webbanhang_webserver:
    image: nginx:alpine
    container_name: webbanhang_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "2215:80"
      - "2216:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - webbanhang-network

  #MySQL Service
  webbanhang_db:
    image: mysql:5.7.22
    container_name: webbanhang_db
    restart: unless-stopped
    tty: true
    ports:
      - "63306:3306"
    environment:
      MYSQL_DATABASE: webbanhang.vn
      MYSQL_ROOT_PASSWORD: Admin@123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webbanhang-network


#Volumes
volumes:
  dbdata:
    driver: local

#Docker Networks
networks:
  webbanhang-network:
    driver: bridge
